./" this is the man page for Bind User Interface - Configuration Handler
.TH bui-cfgh "01/05/2020" "0.0.0" "bui-cfgh man page"

.SH NAME
bui-cfgh - low level command for handlign bind9 configuration

.SH DESCRIPTION
    This is a low level command you should not be using this, use man bui

.SH COMMANDS

.IP addzone
    As the name sugests it adds an authority zone